### ISSUE TITLE
猜年龄游戏外观设计

### ISSUE THREAD

**Issue by 3167049635** [3167049635/TaskManager#1]
我需要设计一个比较整洁的游戏外观

**Comment by HuangHao349** [comment]
收到

**Comment by HuangHao349** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>猜数字游戏</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
        }
        h1 {
            text-align: center;
            color: blue;
        }
        .game-container {
            max-width: 400px;
            margin:0 auto;
            padding: 20px;
            border: 1px solid #ccc;
            border-radius: 5px;
        }
        #result {
            margin-top: 10px;
            font-weight: bold;
        }
    </style>
</head>
<body>
<div class="game-container">
    <h1>猜数字游戏</h1>
    <p>请猜一个1到100之间的数字：</p>
    <input type="number" id="guessInput" min="1" max="100" placeholder="输入你的猜测">
    <button onclick="checkGuess()">猜一猜</button>
    <p id="result"><hr></p>
    <p id="remainingTries">剩余猜测次数：10</p>
    <p id="gameRules">游戏规则：程序已经随机选择了一个1到100之间的数字，你有若干次机会来猜测它。</p>

</div>

<script>
    var targetNumber = Math.floor(Math.random() * 100) + 1;
    var remainingTries = 10;

    function checkGuess() {
        var guessInput = document.getElementById('guessInput');
        var guess = parseInt(guessInput.value);

        if (isNaN(guess) || guess < 1 || guess > 100) {
            document.getElementById('result').textContent = '请输入1到100之间的数字！';
            return;
        }

        if (guess === targetNumber) {
            document.getElementById('result').textContent = '恭喜你，猜对了！';
            resetGame();
        } else if (guess < targetNumber) {
            document.getElementById('result').textContent = '猜的数字太小了！';
            remainingTries--;
            document.getElementById('remainingTries').textContent = '剩余猜测次数：' + remainingTries;

            if (remainingTries === 0) {
                document.getElementById('result').textContent += ' 游戏结束！正确答案是：' + targetNumber;
                resetGame();
            }
        } else {
            document.getElementById('result').textContent = '猜的数字太大了！';
            remainingTries--;
            document.getElementById('remainingTries').textContent = '剩余猜测次数：' + remainingTries;

            if (remainingTries === 0) {
                document.getElementById('result').textContent += ' 游戏结束！正确答案是：' + targetNumber;
                resetGame();
            }
        }

        guessInput.value = '';
    }

    function resetGame() {
        targetNumber = Math.floor(Math.random() * 100) + 1;
        remainingTries = 10;
        document.getElementById('result').textContent = '';
        document.getElementById('remainingTries').textContent = '剩余猜测次数：10';
    }
</script>
</body>
</html>
